"""empty message

Revision ID: 52e9c1abc481
Revises: 
Create Date: 2023-01-24 19:59:49.997921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e9c1abc481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('user_icon', sa.String(), nullable=True),
    sa.Column('profile_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('trade',
    sa.Column('trade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('send_user', sa.Integer(), nullable=True),
    sa.Column('recip_user', sa.Integer(), nullable=True),
    sa.Column('send_skill', sa.Integer(), nullable=True),
    sa.Column('recip_skill', sa.Integer(), nullable=True),
    sa.Column('send_accept', sa.Boolean(), nullable=True),
    sa.Column('recip_accept', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recip_skill'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['recip_user'], ['user_profile.user_id'], ),
    sa.ForeignKeyConstraint(['send_skill'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['send_user'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('skill')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
