"""empty message

Revision ID: a738c3e6d5c5
Revises: ac2d2f142932
Create Date: 2023-01-24 16:38:20.499823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a738c3e6d5c5'
down_revision = 'ac2d2f142932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('skill', 'skill_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('skill_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('skill', 'name')
    # ### end Alembic commands ###
